version: "3"

services:
  back-end:
    container_name: back-end
    build:
      context: .
      dockerfile: app/Dockerfile.dev
    ports: 
      - $BACK_END_PORT:$BACK_END_PORT
    env_file:
      - .env.dev
    volumes: 
      - ./app/conf:/app/conf
      - ./app/routers:/app/routers
      - ./app/schemas:/app/schemas
      - ./app/services:/app/services
      - ./app/alembic:/app/alembic
      - ./tests:/app/tests
