"""add license account model and relation

Revision ID: 7aff3a1d2d00
Revises: e988a6427c4d
Create Date: 2021-02-15 12:07:56.264023

"""

# revision identifiers, used by Alembic.
revision = "7aff3a1d2d00"
down_revision = "a442d3751325"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
