"""first migration

Revision ID: a442d3751325
Revises: 
Create Date: 2021-02-10 20:59:29.319513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a442d3751325"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
