"""update all migrations

Revision ID: f50476681404
Revises: 7aff3a1d2d00
Create Date: 2021-03-24 07:24:28.989958

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f50476681404"
down_revision = "7aff3a1d2d00"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "licenseaccounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("is_using", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "meetings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.String(length=70), nullable=False),
        sa.Column("title", sa.String(length=70), nullable=False),
        sa.Column("calendar_id", sa.String(length=150), nullable=True),
        sa.Column("event_id", sa.String(length=150), nullable=True),
        sa.Column("course_code", sa.String(length=150), nullable=True),
        sa.Column("start_url", sa.String(length=1000), nullable=False),
        sa.Column("join_url", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("email", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["email"],
            ["licenseaccounts.id"],
            name="fk_meetings_licenseaccounts_id_email",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meetings")
    op.drop_table("licenseaccounts")
    # ### end Alembic commands ###
